# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, null=True)),
                ('pwd', models.CharField(max_length=64, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('email', models.EmailField(max_length=32, null=True)),
                ('rg_time', models.DateTimeField(max_length=32, null=True)),
                ('avatar', models.CharField(max_length=128, null=True)),
                ('group', models.IntegerField(choices=[(1, '普通用户'), (2, '黄金会员'), (3, '白金会员'), (4, '至尊会员')])),
            ],
        ),
    ]
