# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, '黄金会员'), (3, '白金会员'), (4, '至尊会员')], default=1),
        ),
    ]
