# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180213_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rg_time',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
