# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180213_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('rid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, null=True)),
                ('pwd', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
