# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('gid', models.BigAutoField(primary_key=True, serialize=False)),
                ('gname', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AddField(
            model_name='groupuser',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
