# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('rid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, null=True)),
                ('pwd', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
