# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('phone', models.IntegerField(max_length=11)),
                ('rg_time', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WebBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockname', models.CharField(max_length=10)),
            ],
        ),
    ]
