# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('aid', models.BigAutoField(primary_key=True, serialize=False)),
                ('article', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('bid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('introduction', models.CharField(max_length=256)),
                ('posttime', models.CharField(max_length=32)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report_system.Article')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report_system.User')),
            ],
        ),
    ]
