# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_system', '0003_auto_20180208_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
