# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BlogArticleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puttime', models.CharField(max_length=32, null=True)),
                ('sort', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogname', models.CharField(max_length=32, null=True)),
                ('rgtime', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512, null=True)),
                ('time', models.CharField(max_length=32, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogArticleInfo')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogArticleInfo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=32, null=True)),
                ('nickname', models.CharField(max_length=32, null=True)),
                ('pwd', models.CharField(max_length=64, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('email', models.EmailField(max_length=32, null=True)),
                ('rg_time', models.CharField(max_length=32, null=True)),
                ('avatar', models.CharField(max_length=128, null=True)),
                ('blogname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogInfo')),
                ('fans', models.ManyToManyField(to='blog.User')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
        migrations.AddField(
            model_name='blogarticleinfo',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogInfo'),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='aid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogArticleInfo'),
        ),
    ]
