# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180226_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticleinfo',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogInfo'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogArticleInfo'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
        migrations.AlterField(
            model_name='like',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogArticleInfo'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='blogname',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogInfo'),
        ),
    ]
