# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180226_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogmodelname', models.CharField(max_length=16, null=True)),
                ('blogmodel', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='blogmodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogModel'),
        ),
    ]
