# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-03 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('作业一', '0002_auto_20180203_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='users',
            name='ug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='作业一.Users'),
        ),
    ]
