# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('作业一', '0004_auto_20180204_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserGirl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=10)),
            ],
        ),
    ]
