# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('作业一', '0005_userboy_usergirl'),
    ]

    operations = [
        migrations.AddField(
            model_name='userboy',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usergirl',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
