# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('作业一', '0006_auto_20180205_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userboy',
            old_name='bname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='usergirl',
            old_name='gname',
            new_name='name',
        ),
    ]
